header-title: 私たちはクラスを行います
logo-list: 
  - logo: /img/video-logo/zoom.png
    title: ZOOM
  - logo: /img/video-logo/skype.png
    title: SKYPE
  - logo: /img/video-logo/zhumu.png
    title: ZHUMU


services: 
  column1:
    title: プロモーション!!!
    subtitle: 500円トライアルクラス
    sub-text: '通常料金:'
    features:
      - item: 1クラス/ 30分= 700円
      - item: 1ヶ月だけ20クラスを登録する 10,000円 (各クラス500円)
    bottom-text: '料金を送る:'
    bottom-logo: /img/video-logo/paypal.png
  
  column2:
    title: 提供されるサービス
    subtitle: すべての年齢
    features:
      - item: 1クラス/ 30分= 700円
      - item: 1ヶ月だけ20クラスを登録する 10,000円 (各クラス500円)
      - item: ビジネス英語
      - item: 英語のアルファベットを学ぶ
      - item: フォニックスサウンド
      - item: 毎日の会話
      - item: 話す
      - item: リスニング
      - item: 読解
      - item: 書く
      - item: Business English
      - item: Writing
      - item: IELTS
      - item: IEKEN
      - item: OPIC
      - item: TOEFL
    bottom-text: '*レベルごとに異なる本があります*'
        


 

